# Generated by Django 4.2.7 on 2023-11-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_duration', models.IntegerField()),
                ('cost', models.FloatField()),
            ],
        ),
    ]
