# Generated by Django 4.2.7 on 2023-11-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingzone', '0002_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='qr_id',
            field=models.CharField(max_length=201, unique=True),
        ),
    ]
