# Generated by Django 4.2.7 on 2023-11-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_slot_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
