# Generated by Django 4.2.7 on 2023-11-21 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingzone', '0001_initial'),
        ('vehicle', '0004_history_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingzone.slot'),
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
