# Generated by Django 4.2.7 on 2023-11-23 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingzone', '0003_alter_zone_qr_id'),
        ('vehicle', '0005_alter_history_slot_delete_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parkingzone.zone'),
            preserve_default=False,
        ),
    ]
